version: "3.3"
services:
  api-gateway-service:
    container_name: api-gateway-service
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-api-gateway-service
    ports:
      - 8989:8989
    networks:
      - postgres
networks:
  postgres:
    name: postgres
    driver: bridge