version: "3.3"
services:
  patient-service:
    container_name: patient-service
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-patient-service
    ports:
      - 8086:8086
    networks:
      - postgres
networks:
  postgres:
    name: postgres
    driver: bridge