version: "3.3"
services:
  healthreport-service:
    container_name: healthreport-service
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-healthreport-service
    ports:
      - 8087:8087
    networks:
      - postgres
networks:
  postgres:
    name: postgres
    driver: bridge