version: "3.3"
services:
  admin-service:
    container_name: admin-service
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-admin-service
    ports:
      - 8084:8084
    networks:
      - postgres
networks:
  postgres:
    name: postgres
    driver: bridge